portezuelo-webapp/config/routes.rb
Tut1::Application.routes.draw do
  
  resources :unidad_productos

  resources :venta

  resources :tipo_ingresos

  resources :tipo_egresos

  resources :tipo_productos

  resources :pedidos

  resources :inventarios

  resources :productos

  resources :negocios

  resources :tipo_mermas

  resources :familia_productos

  get "config/index"
  get "config/tax"
  resources :impuestos

  resources :users
  
  resources :sessions

  get "logout" => "sessions#destroy", :as => "logout"
  get "login" => "sessions#new", :as => "login"

  get "index/home" => "index#home"

  root "sessions#new"

end

portezuelo-webapp/app/models/producto.rb
class Producto < ActiveRecord::Base
	include Filterable
	include Importable
	include Exportable

	self.table_name = 'producto'
	self.per_page = 10
	belongs_to :tipo_producto, :foreign_key => 'id_tipo_producto'
	belongs_to :familia_producto, :class_name => 'FamiliaProducto', :foreign_key => 'familia'
	belongs_to :impuesto, :foreign_key => 'otros_impuestos'
	has_many :inventario_detalle, :class_name => 'InventarioDetalle', :foreign_key => 'barcode'
	has_many :pedido_detalle
	has_many :venta_detalle, :class_name => 'VentaDetalle', :foreign_key => 'barcode'
	has_many :alerta_cambio_precios, :class_name => 'AlertaCambioPrecio'
	has_many :stocks, :class_name => 'Stock', :foreign_key => 'barcode'
	
	# Validations
	validates :barcode, presence: { :message => "Es necesario proporcionar un código de barras" }, uniqueness: { :message => "Este código de barras ya esta registrado" }, numericality: { :only_integer => true, :message => "El código de barras debe estar formado solo por números." }
	validates :codigo_corto, presence: { :message => "Es necesario proporcionar un código corto" }, length: { maximum: 16, :message => "El código corto debe ser como máximo de 16 caracteres" }, uniqueness: { :message => "El código corto ya esta registrado." }
	validates :marca, presence: { :message => "Es necesario proporcionar una marca" }, length: { maximum: 35, :message => "La marca debe ser de como máximo 35 caracteres" } 
	validates :descripcion, presence: { :message => "Es necesario proporcionar una descripción" }, length: { maximum: 50, :message => "La descripción debe ser de como máximo 50 caracteres" }
	validates :contenido, numericality: { only_float: true , greater_than_or_equal_to: 0, message: "El contenido debe ser una cantidad positiva" }
	validates :unidad, length: { maximum: 10, :message => "La unidad debe ser de como máximo 10 caracteres" }
	validates :stock, numericality: { only_float: true , greater_than_or_equal_to: -1, message: "El stock debe ser una cantidad mayor a -1" }
	validates :precio, numericality: { only_float: true , greater_than_or_equal_to: 0, message: "El precio debe ser una cantidad positiva" }
	# validates :precio_neto, numericality: { only_float: true , greater_than_or_equal_to: 0, message: "El precio neto debe ser una cantidad positiva" }
	# validates :costo_promedio, numericality: { only_float: true , greater_than_or_equal_to: 0, message: "El costo promedio debe ser una cantidad positiva" }
	# validates :fifo, <validations>
	# validates :vendidos, <validations>
	# validates :aplica_iva, <validations>
	validates :otros_impuestos, presence: { :message => "Es necesario seleccionar otro impuesto" }
	validates :familia, presence: { :message => "Es necesario proporcionar una familia" }
	validates :id_tipo_producto, presence: { :message => "Es necesario proporcionar un tipo de producto" }
	# validates :es_perecible, <validations>
	# validates :dias_stock, <validations>
	# validates :margen_promedio, <validations>
	# validates :es_venta_fraccionada, <validations>
	# validates :stock_pro, <validations>
	# validates :tasa_canje, <validations>
	# validates :precio_mayor, <validations>
	# validates :cantidad_mayor, <validations>
	# validates :es_mayorista, <validations>
	# validates :estado, <validations>
	# validates :precio_editable, <validations>
	
	# Scopes (used for search form)
	scope :barcode, -> (barcode) { where("barcode = ?", "#{barcode.to_i}") }
	scope :codigo_corto, -> (codigo_corto) { where("codigo_corto = ?", "%#{codigo_corto}%") }
	scope :marca, -> (marca) { where("marca ilike ?", "%#{marca}%") }
	scope :familia, -> (familia) { where("nombre ilike ?", "%#{familia}%").joins(:familia_producto) }
	scope :id_tipo_producto, -> (id_tipo_producto) { where("nombre ilike ?", "%#{id_tipo_producto}%").joins(:tipo_producto) }

	before_update :precio_changed

	def initialize(attributes={})
		attr_with_defaults = { 
			:precio_neto => 0,
			:costo_promedio => 0,
			:vendidos => 0,
			:es_perecible => false,
			:stock_pro => 0,
			:aplica_iva => true,
			:stock => 0
		}.merge(attributes)
		super(attr_with_defaults)
	end

	def precio_changed
		if self.changed.include?('precio')
			Negocio.all.each do |negocio|
				AlertaCambioPrecio.new(
					:negocio_id => negocio.id,
					:barcode => self.barcode,
					:leido => false,
					:descripcion => "Se ha actualizado el precio del producto '#{self.descripcion}' quedando a un valor de $#{self.changes["precio"][1]} (antes valía $#{self.changes["precio"][0]})",
					:precio_antiguo => self.changes["precio"][0],
					:precio_nuevo => self.changes["precio"][1],
					:fecha => Time.new
				).save
			end
		end
	end

	def get_last_stocks
		months = ['Ene','Feb','Mar','Abr','May','Jun','Jul','Ago','Sep','Oct','Nov','Dic']
		stats = []
		labels = []
		Negocio.all.each do |n|
			query = ActiveRecord::Base.connection.execute("
				SELECT 
				EXTRACT(YEAR FROM stocks.fecha) AS anio, 
				EXTRACT(MONTH FROM stocks.fecha) AS mes, 
				AVG(stocks.cantidad) AS cantidad 
				FROM producto 
				INNER JOIN stocks ON (stocks.barcode = producto.barcode) 
				INNER JOIN negocio ON (stocks.negocio_id = negocio.id) 
				WHERE negocio.id = #{n.id} 
				AND producto.barcode = #{self.barcode} 
				AND stocks.fecha >= CURRENT_DATE - interval '6 months' 
				AND stocks.fecha <= CURRENT_DATE
				GROUP BY mes, anio
				ORDER BY anio, mes
				".tr("\n", " "))
			data = []
			
			query.each do |avg|
				data.push(avg["cantidad"].to_f)
				labels.push(months[avg["mes"].to_i-1] + ", " + avg["anio"]) if labels.count != 6
			end

			stats.push({
				:name => "#{n.nombre}",
				:data => data
			})
		end
		labels = [] if labels.count != 6
		return { :labels => labels, :stats => stats }
	end

	def get_last_sells
		months = ['Ene','Feb','Mar','Abr','May','Jun','Jul','Ago','Sep','Oct','Nov','Dic']
		stats = []
		labels = []
		Negocio.all.each do |n|
			query = ActiveRecord::Base.connection.execute("
				SELECT 
				EXTRACT(YEAR FROM venta.fecha) AS anio, 
				EXTRACT(MONTH FROM venta.fecha) AS mes, 
				SUM(venta_detalle.cantidad) AS cantidad 
				FROM venta 
				INNER JOIN venta_detalle ON (venta_detalle.venta_id = venta.id) 
				INNER JOIN producto ON (venta_detalle.barcode = producto.barcode) 
				INNER JOIN negocio ON (venta.negocio_id = negocio.id) 
				WHERE producto.barcode = #{self.barcode} 
				AND negocio.id = #{n.id} 
				AND venta.fecha >= CURRENT_DATE - INTERVAL '6 months' 
				AND venta.fecha <= CURRENT_DATE 
				GROUP BY mes, anio 
				ORDER BY anio, mes
				".tr("\n", " "))
			data = []

			query.each do |sum|
				data.push(sum["cantidad"].to_f)
				labels.push(months[sum["mes"].to_i-1] + ", " + sum["anio"]) if labels.count != 6
			end

			stats.push({
				:name => "#{n.nombre}",
				:data => data
			})
		end
		labels = [] if labels.count != 6
		return { :labels => labels, :stats => stats }
	end

end

portezuelo-webapp/app/controllers/productos_controller.rb
class ProductosController < ApplicationController
  before_action :set_producto, only: [:show, :edit, :update, :destroy]
  
  # GET /productos
  def index
    @productos = Producto.filter(
      params.slice(:barcode, :codigo_corto, :marca, :familia, :id_tipo_producto)
    ).paginate :page => params[:page]
  end

  # GET /productos/1
  def show
  end

  # GET /productos/new
  def new
    @producto = Producto.new
  end

  # GET /productos/1/edit
  def edit
  end

  # POST /productos
  def create
    @producto = Producto.new(producto_params)

    if @producto.save
      redirect_to @producto, notice: 'El producto ha sido creado de forma exitosa.'
    else
      render :new
    end
  end

  # PATCH/PUT /productos/1
  def update
    if @producto.update(producto_params)
      redirect_to @producto, notice: 'El producto ha sido actualizado de forma exitosa.'
    else
      render :edit
    end
  end

  # DELETE /productos/1
  def destroy
    @producto.destroy
    redirect_to productos_url, notice: 'El producto ha sido eliminado.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_producto
      @producto = Producto.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def producto_params
      params.require(:producto).permit(:barcode, :codigo_corto, :marca, :descripcion, :contenido, :unidad, :stock, :precio, :precio_neto, :costo_promedio, :fifo, :vendidos, :aplica_iva, :otros_impuestos, :familia, :id_tipo_producto, :es_perecible, :dias_stock, :margen_promedio, :es_venta_fraccionada, :stock_pro, :tasa_canje, :precio_mayor, :cantidad_mayor, :es_mayorista, :estado, :precio_editable)
    end
end

portezuelo-webapp/app/helpers/productos_helper.rb
module ProductosHelper
end

portezuelo-webapp/app/views/productos/_form.html.erb
<%= form_for(@producto) do |f| %>
<% if @producto.errors.any? %>
<div class="alert alert-danger">
    <ul>
        <% @producto.errors.messages.each do |msg| %>
        <li><%= msg[1][0] %></li>
        <% end %>    
    </ul>
</div>
<% end %>

<div class="row">
    <div class="col-md-6">
        <div class="form-group">
            <%= f.label 'Código de barras' %>
            <%= f.text_field :barcode, :class => "form-control" %>
        </div>
        <div class="form-group">
            <%= f.label :codigo_corto %>
            <%= f.text_field :codigo_corto, :class => "form-control" %>
        </div>
        <div class="form-group">
            <%= f.label :marca %>
            <%= f.text_field :marca, :class => "form-control" %>
        </div>
        <div class="form-group">
            <%= f.label :descripcion %>
            <%= f.text_field :descripcion, :class => "form-control" %>
        </div>
        <div class="form-group">
            <%= f.label :contenido %>
            <%= f.text_field :contenido, :class => "form-control" %>
        </div>
        <div class="form-group">
            <%= f.label :unidad %>
            <%= f.collection_select :unidad, UnidadProducto.all, :nombre, :nombre, { prompt: true }, { :class => 'form-control' } %>
        </div>
        <div class="form-group">
            <%= f.label :precio %>
            <%= f.text_field :precio, :class => "form-control" %>
        </div>
    </div>
    <div class="col-md-6">
        <div class="form-group">
            <%= f.label :aplica_iva %>
            <%= f.check_box :aplica_iva, :class => "form-control" %>
        </div>
        <div class="form-group">
            <%= f.label :otros_impuestos %>
            <%= f.collection_select :otros_impuestos, Impuesto.all, :id, :descripcion, { prompt: true }, { :class => 'form-control' } %>
        </div>
        <div class="form-group">
            <%= f.label :familia %>
            <%= f.collection_select :familia, FamiliaProducto.all, :id, :nombre, { prompt: true }, { :class => 'form-control' } %>
        </div>
        <div class="form-group">
            <%= f.label 'Tipo producto' %>
            <%= f.collection_select :id_tipo_producto, TipoProducto.all, :id, :nombre, { prompt: true }, { :class => 'form-control' } %>
        </div>
        <div class="form-group">
            <%= f.label :es_perecible %>
            <%= f.check_box :es_perecible, :class => "form-control" %>
        </div>  
        <div class="form-group">
            <%= f.label :es_venta_fraccionada %>
            <%= f.check_box :es_venta_fraccionada, :class => "form-control" %>
        </div>
        <div class="form-group">
            <%= f.label :precio_editable %>
            <%= f.check_box :precio_editable, :class => "form-control" %>
        </div>        
    </div>
</div>

<div class="actions">
    <%= f.submit :class => "btn btn-success" %>
</div>

<% end %>

portezuelo-webapp/app/views/productos/_form_edit.html.erb
<%= form_for(@producto) do |f| %>
<% if @producto.errors.any? %>
<div class="alert alert-danger">
    <ul>
        <% @producto.errors.messages.each do |msg| %>
        <li><%= msg[1][0] %></li>
        <% end %>    
    </ul>
</div>
<% end %>

<div class="row">
    <div class="col-md-6">
        <div class="form-group">
            <%= f.label 'Código de barras' %>
            <%= f.text_field :barcode, :class => "form-control", :disabled => "true" %>
        </div>
        <div class="form-group">
            <%= f.label :codigo_corto %>
            <%= f.text_field :codigo_corto, :class => "form-control" %>
        </div>
        <div class="form-group">
            <%= f.label :marca %>
            <%= f.text_field :marca, :class => "form-control" %>
        </div>
        <div class="form-group">
            <%= f.label :descripcion %>
            <%= f.text_field :descripcion, :class => "form-control" %>
        </div>
        <div class="form-group">
            <%= f.label :contenido %>
            <%= f.text_field :contenido, :class => "form-control" %>
        </div>
        <div class="form-group">
            <%= f.label :unidad %>
            <%= f.collection_select :unidad, UnidadProducto.all, :nombre, :nombre, { prompt: true }, { :class => 'form-control' } %>
        </div>
        <div class="form-group">
            <%= f.label :precio %>
            <%= f.text_field :precio, :class => "form-control" %>
        </div>
    </div>
    <div class="col-md-6">
        <div class="form-group">
            <%= f.label :aplica_iva %>
            <%= f.check_box :aplica_iva, :class => "form-control" %>
        </div>
        <div class="form-group">
            <%= f.label :otros_impuestos %>
            <%= f.collection_select :otros_impuestos, Impuesto.all, :id, :descripcion, { prompt: true }, { :class => 'form-control' } %>
        </div>
        <div class="form-group">
            <%= f.label :familia %>
            <%= f.collection_select :familia, FamiliaProducto.all, :id, :nombre, { prompt: true }, { :class => 'form-control' } %>
        </div>
        <div class="form-group">
            <%= f.label 'Tipo producto' %>
            <%= f.collection_select :id_tipo_producto, TipoProducto.all, :id, :nombre, { prompt: true }, { :class => 'form-control' } %>
        </div>
        <div class="form-group">
            <%= f.label :es_perecible %>
            <%= f.check_box :es_perecible, :class => "form-control" %>
        </div>  
        <div class="form-group">
            <%= f.label :es_venta_fraccionada %>
            <%= f.check_box :es_venta_fraccionada, :class => "form-control" %>
        </div>
        <div class="form-group">
            <%= f.label :precio_editable %>
            <%= f.check_box :precio_editable, :class => "form-control" %>
        </div>        
    </div>
</div>

<div class="actions">
    <%= f.submit :class => "btn btn-success" %>
</div>

<% end %>

portezuelo-webapp/app/views/productos/edit.html.erb
<h2 class="page-title page-title-green">
  <span class="glyphicon glyphicon-align-left"></span>
  Productos
</h2>

<div class="page-body">
	<div class="row">
		<div class="col-md-8 col-md-offset-2">
			<div class="panel panel-primary">
				<div class="panel-heading">Editar producto</div>
				<div class="panel-body">
					<%= render 'form_edit' %>					
				</div>
			</div>
			<%= link_to 'Ver detalle', @producto, :class => "bnt btn-link" %> |
			<%= link_to 'Volver', productos_path, :class => "btn btn-link" %>			
		</div>
	</div>
</div>

portezuelo-webapp/app/views/productos/index.html.erb
<h2 class="page-title page-title-green">
  <span class="glyphicon glyphicon-align-left"></span>
  Productos
</h2>

<div class="page-buttons clearfix">
  <%= link_to 'Nuevo Producto', new_producto_path, :class => "btn btn-primary" %>
  <%= render :partial => 'shared/search', :locals => { 
    :filters => { 
      :barcode => 'Código de barras', 
      :codigo_corto => 'Código corto',
      :marca => 'Marca',
      :familia => 'Familia',
      :id_tipo_producto => 'Tipo de producto'
    }
  } %>
  <%= link_to 'Mostrar todos', productos_path, :class => "btn btn-default float-right" %>
</div>

<div class="page-body">
  <div class="panel panel-default">
    <div class="panel-body">
      <div class="table-responsive">

        <table class="table table-hover">
          <thead>
            <tr>
              <th>Código de barras</th>
              <th>Codigo corto</th>
              <th>Marca</th>
              <th>Stock</th>
              <th>Precio</th>
              <th>Familia</th>
              <th>Tipo</th>
              <th></th>
            </tr>
          </thead>

          <tbody>
            <% @productos.each do |producto| %>
            <tr>
              <td><%= producto.barcode %></td>
              <td><%= producto.codigo_corto %></td>
              <td><%= producto.marca %></td>
              <td><%= producto.stock %></td>
              <td>$ <%= producto.precio.to_s.reverse.gsub(/(\d{3})(?=\d)/, '\\1,').reverse %></td>
              <td><%= producto.familia_producto.nombre %></td>
              <td><%= producto.tipo_producto.nombre %></td>
              <td><%= link_to '', producto, :class => "btn btn-default glyphicon glyphicon-eye-open" %></td>
            </tr>
            <% end %>
          </tbody>
        </table>

        <div class="pagination">
          <%= will_paginate @posts, renderer: BootstrapPagination::Rails %>
        </div>
      </div>
    </div>
  </div>
</div>



<br>

portezuelo-webapp/app/views/productos/new.html.erb
<h2 class="page-title page-title-green">
  <span class="glyphicon glyphicon-align-left"></span>
  Productos
</h2>

<div class="page-body">
	<div class="row">
		<div class="col-md-8 col-md-offset-2">
			<div class="panel panel-primary">
				<div class="panel-heading">Nuevo producto</div>
				<div class="panel-body">
					<%= render 'form' %>					
				</div>
			</div>
			<%= link_to 'Volver', productos_path, :class => "btn btn-link" %>
		</div>
	</div>
</div>

portezuelo-webapp/app/views/productos/show.html.erb
<h2 class="page-title page-title-green">
	<span class="glyphicon glyphicon-align-left"></span>
	Productos
</h2>

<% if notice -%>
<div class="alert alert-info"><%= notice %></div>
<% end -%>

<div class="page-body">
	<div class="row">
		<div class="col-md-12">
			<div class="panel panel-primary">
				<div class="panel-heading">Detalle producto</div>
				<div class="panel-body">

					<div class="row">
						<div class="col-md-6">
							<table class="table">
								<tr>
									<th>Codigo de barras:</th>
									<td><%= @producto.barcode %></td>
								</tr>
								<tr>
									<th>Codigo corto:</th>
									<td><%= @producto.codigo_corto %></td>
								</tr>
								<tr>
									<th>Marca:</th>
									<td><%= @producto.marca %></td>
								</tr>
								<tr>
									<th>Descripcion:</th>
									<td><%= @producto.descripcion %></td>
								</tr>
								<tr>
									<th>Contenido:</th>
									<td><%= @producto.contenido %></td>
								</tr>
								<tr>
									<th>Unidad:</th>
									<td><%= @producto.unidad %></td>
								</tr>
								<tr>
									<th>Precio:</th>
									<td>$ <%= @producto.precio.to_s.reverse.gsub(/(\d{3})(?=\d)/, '\\1,').reverse %></td>
								</tr>
								<tr>
									<th>Vendidos:</th>
									<td><%= @producto.vendidos %></td>	
								</tr>
								<tr>
									<th>Aplica iva:</th>
									<td>
										<% if @producto.aplica_iva %>
										Sí
										<% else %>
										No
										<% end %>
									</td>	
								</tr>
							</table>
						</div>
						<div class="col-md-6">
							<table class="table">
								<tr>
									<th>Otros impuestos:</th>
									<td><%= @producto.impuesto.descripcion %></td>	
								</tr>
								<tr>
									<th>Familia:</th>
									<td><%= @producto.familia_producto.nombre %></td>	
								</tr>
								<tr>
									<th>Tipo de producto:</th>
									<td><%= @producto.tipo_producto.nombre %></td>	
								</tr>
								<tr>
									<th>Es perecible:</th>
									<td>
										<% if @producto.es_perecible %>
										Sí
										<% else %>
										No
										<% end %>
									</td>	
								</tr>
								<tr>
									<th>Dias stock:</th>
									<td><%= @producto.dias_stock %></td>	
								</tr>
								<tr>
									<th>Margen promedio:</th>
									<td><%= @producto.margen_promedio %></td>	
								</tr>
								<tr>
									<th>Es venta fraccionada:</th>
									<td>
										<% if @producto.es_venta_fraccionada %>
										Sí
										<% else %>
										No
										<% end %>
									</td>	
								</tr>
								<tr>
									<th>Stock pro:</th>
									<td><%= @producto.stock_pro %></td>	
								</tr>
								<tr>
									<th>Tasa canje:</th>
									<td><%= @producto.tasa_canje %></td>	
								</tr>
								<tr>
									<th>Precio editable:</th>
									<td>
										<% if @producto.precio_editable %>
										Sí
										<% else %>
										No
										<% end %>
									</td>	
								</tr>
							</table>
						</div>
					</div>

					<%= link_to 'Editar', edit_producto_path(@producto), :class => "btn btn-default" %>
					<!--<%= link_to 'Eliminar', @producto, method: :delete, data: { confirm: 'Are you sure?' }, :class => "btn btn-danger" %>-->
					<%= link_to 'Volver', productos_path, :class => "btn btn-link" %>

				</div>
			</div>
		</div>
	</div>
	<div class="row">
		<div class="col-md-6">
			<div id="stock" style="min-width: 100%; height: 400px; margin: 0 auto"></div>
			<script type="text/javascript">
				$(function () {
					$('#stock').highcharts({
						title: {
							text: 'Stock por local',
			                x: 0 //center
			            },
			            xAxis: {
			            	categories: <%= raw @producto.get_last_stocks[:labels].to_json %>
			            },
			            yAxis: {
			            	min: 0,
			            	title: {
			            		text: 'Unidades (UN)'
			            	},
			            	plotLines: [{
			            		value: 0,
			            		width: 1,
			            		color: '#808080'
			            	}]
			            },
			            tooltip: {
			            	valueSuffix: 'UN'
			            },
			            legend: {
			            	layout: 'vertical',
			            	align: 'right',
			            	verticalAlign: 'middle',
			            	borderWidth: 0
			            },
			            series: <%= raw @producto.get_last_stocks[:stats].to_json %>
			        });
				});
			</script>
		</div>
		<div class="col-md-6">
			<div id="ventas" style="min-width: 100%; height: 400px; margin: 0 auto"></div>
			<script type="text/javascript">
				$(function () {
					$('#ventas').highcharts({
						title: {
							text: 'Ventas por local',
			                x: 0
			            },
			            xAxis: {
			            	categories: <%= raw @producto.get_last_sells[:labels].to_json %>
			            },
			            yAxis: {
			            	min: 0,
			            	title: {
			            		text: 'Unidades (UN)'
			            	},
			            	plotLines: [{
			            		value: 0,
			            		width: 1,
			            		color: '#808080'
			            	}]
			            },
			            tooltip: {
			            	valueSuffix: 'UN'
			            },
			            legend: {
			            	layout: 'vertical',
			            	align: 'right',
			            	verticalAlign: 'middle',
			            	borderWidth: 0
			            },
			            series: <%= raw @producto.get_last_sells[:stats].to_json %>
			        });
				});
			</script>
		</div>
		</div>
	</div>
</div>