portezuelo-webapp/config/routes.rb
Tut1::Application.routes.draw do
  
  resources :unidad_productos

  resources :venta

  resources :tipo_ingresos

  resources :tipo_egresos

  resources :tipo_productos

  resources :pedidos

  resources :inventarios

  resources :productos

  resources :negocios

  resources :tipo_mermas

  resources :familia_productos

  get "config/index"
  get "config/tax"
  resources :impuestos

  resources :users
  
  resources :sessions

  get "logout" => "sessions#destroy", :as => "logout"
  get "login" => "sessions#new", :as => "login"

  get "index/home" => "index#home"

  root "sessions#new"

end

portezuelo-webapp/app/models/tipo_merma.rb
class TipoMerma < ActiveRecord::Base
	self.table_name = 'tipo_merma'
	self.per_page = 10

	include Filterable
	include Importable
	include Exportable

		
	# Validations
	validates :nombre, presence: { :message => "Es necesario proporcionar un nombre de mínimo 4 caracteres" }, length: { minimum: 4, maximum: 128, message: "El nombre debe tener como mínimo 4 caracteres y como máximo 128" }
	
	# Scopes (used for search form)
	#   To search by full text use { where("attribute like ?", "%#{attribute}%") }
	#   To search by string use { where attribute: attribute }
		scope :nombre, -> (nombre) { where nombre: nombre }
	
end

portezuelo-webapp/app/controllers/tipo_mermas_controller.rb
class TipoMermasController < ApplicationController
  before_action :set_tipo_merma, only: [:show, :edit, :update, :destroy]

  # GET /tipo_mermas
  def index
    @tipo_mermas = TipoMerma.paginate :page => params[:page]
  end

  # GET /tipo_mermas/1
  def show
  end

  # GET /tipo_mermas/new
  def new
    @tipo_merma = TipoMerma.new
  end

  # GET /tipo_mermas/1/edit
  def edit
  end

  # POST /tipo_mermas
  def create
    @tipo_merma = TipoMerma.new(tipo_merma_params)

    if @tipo_merma.save
      redirect_to @tipo_merma, notice: 'Tipo merma was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /tipo_mermas/1
  def update
    if @tipo_merma.update(tipo_merma_params)
      redirect_to @tipo_merma, notice: 'Tipo merma was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /tipo_mermas/1
  def destroy
    @tipo_merma.destroy
    redirect_to tipo_mermas_url, notice: 'Tipo merma was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_tipo_merma
      @tipo_merma = TipoMerma.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def tipo_merma_params
      params.require(:tipo_merma).permit(:nombre)
    end
end

portezuelo-webapp/app/helpers/tipo_mermas_helper.rb
module TipoMermasHelper
end

portezuelo-webapp/app/views/tipo_mermas/_form.html.erb
<%= form_for(@tipo_merma) do |f| %>
<% if @tipo_merma.errors.any? %>
    <div class="alert alert-danger">
        <ul>
            <% @tipo_merma.errors.messages.each do |msg| %>
            <li><%= msg[1][0] %></li>
            <% end %>    
        </ul>
    </div>
<% end %>

<div class="form-group">
                <%= f.label :nombre %>
            <%= f.text_field :nombre, :class => "form-control" %>
    </div>
<div class="actions">
    <%= f.submit :class => "btn btn-success" %>
</div>
<% end %>

portezuelo-webapp/app/views/tipo_mermas/edit.html.erb
<%= render partial: "/config/header" %>

<div class="page-body">
	<div class="row">
		<div class="col-md-8 col-md-offset-2">
			<div class="panel panel-primary">
				<div class="panel-heading">Nuevo</div>
				<div class="panel-body">
					<%= render 'form' %>					
				</div>
			</div>
			<%= link_to 'Show', @tipo_merma, :class => "bnt btn-link" %> |
			<%= link_to 'Back', tipo_mermas_path, :class => "btn btn-link" %>			
		</div>
	</div>
</div>

portezuelo-webapp/app/views/tipo_mermas/index.html.erb
<%= render partial: "/config/header" %>

<div class="page-buttons clearfix">
  <%= link_to 'Nuevo Tipo de merma', new_tipo_merma_path, :class => "btn btn-primary" %>
</div>

<div class="page-body">
  <div class="panel panel-default">
    <div class="panel-body">
      <div class="table-responsive">

        <table class="table table-hover">
          <thead>
            <tr>
              <th>Nombre</th>
              <th></th>
            </tr>
          </thead>

          <tbody>
            <% @tipo_mermas.each do |tipo_merma| %>
            <tr>
              <td><%= tipo_merma.nombre %></td>
              <td><%= link_to '', tipo_merma, :class => "btn btn-default glyphicon glyphicon-eye-open" %></td>
            </tr>
            <% end %>
          </tbody>
        </table>

        <div class="pagination">
          <%= will_paginate @posts, renderer: BootstrapPagination::Rails %>
        </div>
      </div>
    </div>
  </div>
</div>



<br>

portezuelo-webapp/app/views/tipo_mermas/new.html.erb
<%= render partial: "/config/header" %>

<div class="page-body">
	<div class="row">
		<div class="col-md-8 col-md-offset-2">
			<div class="panel panel-primary">
				<div class="panel-heading">Nuevo</div>
				<div class="panel-body">
					<%= render 'form' %>					
				</div>
			</div>
			<%= link_to 'Back', tipo_mermas_path, :class => "btn btn-link" %>
		</div>
	</div>
</div>

portezuelo-webapp/app/views/tipo_mermas/show.html.erb
<%= render partial: "/config/header" %>

<% if notice -%>
<div class="alert alert-info"><%= notice %></div>
<% end -%>

<div class="page-body">
	<div class="row">
		<div class="col-md-8 col-md-offset-2">
			<div class="panel panel-primary">
				<div class="panel-heading">Detalle</div>
				<div class="panel-body">
					
					<table class="table">
						<tbody>
													<tr>
							  <th>Nombre:</th>
							  <td><%= @tipo_merma.nombre %></td>
							</tr>
												</tbody>
					</table>

					<%= link_to 'Edit', edit_tipo_merma_path(@tipo_merma), :class => "btn btn-default" %>
					<%= link_to 'Destroy', @tipo_merma, method: :delete, data: { confirm: 'Are you sure?' }, :class => "btn btn-danger" %>
					<%= link_to 'Back', tipo_mermas_path, :class => "btn btn-link" %>

				</div>
			</div>
		</div>
	</div>
</div>