portezuelo-webapp/config/routes.rb
Tut1::Application.routes.draw do
  
  resources :unidad_productos

  resources :venta

  resources :tipo_ingresos

  resources :tipo_egresos

  resources :tipo_productos

  resources :pedidos

  resources :inventarios

  resources :productos

  resources :negocios

  resources :tipo_mermas

  resources :familia_productos

  get "config/index"
  get "config/tax"
  resources :impuestos

  resources :users
  
  resources :sessions

  get "logout" => "sessions#destroy", :as => "logout"
  get "login" => "sessions#new", :as => "login"

  get "index/home" => "index#home"

  root "sessions#new"

end

portezuelo-webapp/app/models/inventario.rb
class Inventario < ActiveRecord::Base
	self.table_name = 'inventario'
	self.per_page = 10
	belongs_to :negocio
	belongs_to :user
	has_many :inventario_detalles, :class_name => "InventarioDetalle"

	include Filterable
	include Importable
	include Exportable

		
	# Validations
	# validates :negocio_id, <validations>
	# validates :user_id, <validations>
	# validates :fecha, <validations>
	
	# Scopes (used for search form)
	scope :usuario, -> (usuario) { where("nombre ilike ? or rut ilike ?", "%#{usuario}%", "%#{usuario}%").joins(:user) }
	scope :negocio, -> (negocio) { where("nombre ilike ?", "%#{negocio}%").joins(:negocio) }
	
end

portezuelo-webapp/app/controllers/inventarios_controller.rb
class InventariosController < ApplicationController
  before_action :set_inventario, only: [:show, :edit, :update, :destroy]

  # GET /inventarios
  def index
    @inventarios = Inventario.all.order('fecha desc').filter(
      params.slice(:usuario, :negocio)
    ).paginate :page => params[:page]
  end

  # GET /inventarios/1
  def show
    @detalles = InventarioDetalle.where("inventario_id = ?", "#{@inventario.id}").filter(
      params.slice(:marca, :familia, :tipo)
    )
  end

  # GET /inventarios/new
  def new
    @inventario = Inventario.new
  end

  # GET /inventarios/1/edit
  def edit
  end

  # POST /inventarios
  def create
    @inventario = Inventario.new(inventario_params)

    if @inventario.save
      redirect_to @inventario, notice: 'Inventario was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /inventarios/1
  def update
    if @inventario.update(inventario_params)
      redirect_to @inventario, notice: 'Inventario was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /inventarios/1
  def destroy
    @inventario.destroy
    redirect_to inventarios_url, notice: 'Inventario was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_inventario
      @inventario = Inventario.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def inventario_params
      params.require(:inventario).permit(:negocio_id, :user_id, :fecha)
    end
end

portezuelo-webapp/app/helpers/inventarios_helper.rb
module InventariosHelper
end

portezuelo-webapp/app/views/inventarios/_form.html.erb
<%= form_for(@inventario) do |f| %>
<% if @inventario.errors.any? %>
<div class="alert alert-danger">
    <ul>
        <% @inventario.errors.messages.each do |msg| %>
        <li><%= msg[1][0] %></li>
        <% end %>    
    </ul>
</div>
<% end %>

<div class="form-group">
    <%= f.label :negocio_id %>
    <%= f.collection_select :negocio_id, Negocio.all, :id, :nombre, { prompt: true }, { :class => 'form-control' } %>
</div>
<div class="form-group">
    <%= f.label 'Usuario' %>
    <%= f.collection_select :user_id, User.all, :id, :nombre, { prompt: true }, { :class => 'form-control' } %>
</div>
<div class="form-group">
    <%= f.label :fecha %>
    <%= f.datetime_select :fecha, :class => "form-control" %>
</div>
<div class="actions">
    <%= f.submit :class => "btn btn-success" %>
</div>
<% end %>

portezuelo-webapp/app/views/inventarios/edit.html.erb
<h2 class="page-title page-title-green">
	<span class="glyphicon glyphicon-th"></span>
	Inventario
</h2>

<div class="page-body">
	<div class="row">
		<div class="col-md-8 col-md-offset-2">
			<div class="panel panel-primary">
				<div class="panel-heading">Nuevo</div>
				<div class="panel-body">
					<%= render 'form' %>					
				</div>
			</div>
			<%= link_to 'Show', @inventario, :class => "bnt btn-link" %> |
			<%= link_to 'Back', inventarios_path, :class => "btn btn-link" %>			
		</div>
	</div>
</div>

portezuelo-webapp/app/views/inventarios/index.html.erb
<h2 class="page-title page-title-green">
  <span class="glyphicon glyphicon-th"></span>
  Inventario
</h2>

<div class="page-buttons clearfix">
  <!--<%= link_to 'Nuevo inventario', new_inventario_path, :class => "btn btn-primary" %>-->
  <%= render :partial => 'shared/search', :locals => { 
    :filters => { 
      :usuario => 'Usuario', 
      :negocio => 'Negocio'
    }
  } %>
  <%= link_to 'Mostrar todos', inventarios_path, :class => "btn btn-default float-right" %>
</div>

<div class="page-body">
  <div class="panel panel-default">
    <div class="panel-body">
      <div class="table-responsive">

        <table class="table table-hover">
          <thead>
            <tr>
              <th>Negocio</th>
              <th>Usuario</th>
              <th>Fecha</th>
              <th></th>
            </tr>
          </thead>

          <tbody>
            <% @inventarios.each do |inventario| %>
            <tr>
              <td><%= inventario.negocio.nombre %></td>
              <td>
                <%= inventario.user.rut %> - 
                <%= inventario.user.nombre %>
              </td>
              <td><%= inventario.fecha %></td>
              <td><%= link_to '', inventario, :class => "btn btn-default glyphicon glyphicon-eye-open" %></td>
            </tr>
            <% end %>
          </tbody>
        </table>

        <div class="pagination">
          <%= will_paginate @posts, renderer: BootstrapPagination::Rails %>
        </div>
      </div>
    </div>
  </div>
</div>



<br>

portezuelo-webapp/app/views/inventarios/new.html.erb
<h2 class="page-title page-title-green">
	<span class="glyphicon glyphicon-th"></span>
	Inventario
</h2>

<div class="page-body">
	<div class="row">
		<div class="col-md-8 col-md-offset-2">
			<div class="panel panel-primary">
				<div class="panel-heading">Nuevo</div>
				<div class="panel-body">
					<%= render 'form' %>					
				</div>
			</div>
			<%= link_to 'Volver', inventarios_path, :class => "btn btn-link" %>
		</div>
	</div>
</div>

portezuelo-webapp/app/views/inventarios/show.html.erb
<h2 class="page-title page-title-green">
	<span class="glyphicon glyphicon-th"></span>
	Inventario
</h2>

<% if notice -%>
<div class="alert alert-info"><%= notice %></div>
<% end -%>

<div class="page-body">
	<div class="row">
		<div class="col-md-4">
			<div class="panel panel-primary">
				<div class="panel-heading">Detalle inventario</div>
				<div class="panel-body">

					<table class="table">
						<tbody>
							<tr>
								<th>Negocio:</th>
								<td>
									<%= @inventario.negocio.nombre %>
								</td>
							</tr>
							<tr>
								<th>Usuario:</th>
								<td>
									<%= @inventario.user.rut %> - 
									<%= @inventario.user.nombre %>
								</td>
							</tr>
							<tr>
								<th>Fecha:</th>
								<td><%= @inventario.fecha %></td>
							</tr>
						</tbody>
					</table>
					
					<!--
					<%= link_to 'Editar', edit_inventario_path(@inventario), :class => "btn btn-default" %>
					<%= link_to 'Eliminar', @inventario, method: :delete, data: { confirm: 'Are you sure?' }, :class => "btn btn-danger" %>-->
					<%= link_to 'Volver', inventarios_path, :class => "btn btn-link" %>

				</div>
			</div>
		</div>
		<div class="col-md-8">
			<div class="panel panel-primary">
				<div class="panel-heading">Conteo de productos</div>
				<div class="panel-body">
					<div class="clearfix" style="margin-bottom: 15px;">
						<%= render :partial => 'shared/search', :locals => { 
							:filters => {
								:marca => 'Marca',
								:familia => 'Familia',
								:tipo => 'Tipo producto'
							}
						} %>
						<%= link_to 'Mostrar todos', @inventario, :class => "btn btn-default float-right" %>
					</div>
					<table class="table">
						<tr>
							<th>Código de barras</th>
							<th>Marca</th>
							<th>Descripción</th>
							<th>Familia</th>
							<th>Tipo</th>
							<th>Cantidad</th>
						</tr>
						<% @detalles.each do |detalle| %>
							<tr>
								<td><%= detalle.barcode %></td>
								<td><%= detalle.producto.marca %></td>
								<td><%= detalle.producto.descripcion %></td>
								<td><%= detalle.producto.familia_producto.nombre %></td>
								<td><%= detalle.producto.tipo_producto.nombre %></td>
								<td><%= detalle.cantidad %></td>
							</tr>
						<% end %>
					</table>

				</div>
			</div>
		</div>
	</div>
</div>